# Generated by Django 4.2.1 on 2023-05-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='projectId',
            new_name='project',
        ),
    ]
